name: Test Python

on:
  pull_request_review:
    types:
    - submitted
    branches:
    - master
    paths:
    - '**.py'
    - 'src/**'
    - 'setup.cfg'
    - 'tox.ini'
    - 'examples/**'
  push:
    branches:
    - master
    paths:
    - '**.py'
    - 'src/**'
    - 'setup.cfg'
    - 'tox.ini'
    - 'examples/**'
    tags-ignore:
    - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event.review.state == 'approved'
    steps:

    - uses: actions/checkout@v2

    - name: Set up python environment
      uses: actions/setup-python@v2
      with:
        python-version: 3.6

    - name: Install Tox
      run: |
        python -m pip install --upgrade pip setuptools wheel tox

    - name: Run tests
      run: |
        tox -e test,report

    - name: Upload coverage reports
      uses: codecov/codecov-action@v1
